source 'https://rubygems.org'

gem 'spree', github: 'spree/spree', branch: 'master'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', branch: 'master'
gem 'spree_frontend_bootstrap', path: '../spree_frontend_bootstrap'

gemspec
