source 'https://rubygems.org'

gem 'spree', github: 'spree/spree', branch: 'b07b838'
gem 'spree_auth_devise', github: 'spree/spree_auth_devise', ref: 'acb4560c1de6c75e8b675ec5cd5a8cd7d21e4f2c'
gem 'spree_bootstrap', path: '../spree_bootstrap'

gemspec
