source 'https://rubygems.org'

spree_branch = 'master'
# Provides basic authentication functionality for testing parts of your engine
gem 'spree', github: 'spree/spree', branch: spree_branch

gemspec
